/*
	Lección 16 - Funciones de FECHA y HORA
*/


-- UTC

--HIGHER 
SELECT SYSDATETIME()		AS 'SYSDATETIME'
SELECT SYSDATETIMEOFFSET()	AS 'SYSDATETIMEOFFSET'
SELECT SYSUTCDATETIME()		AS 'SYSUTCDATETIME'


--LOWER
SELECT GETDATE()			AS 'GETDATE'
SELECT CURRENT_TIMESTAMP	AS 'CURRENT_TIMESTAMP'
SELECT GETUTCDATE()			AS 'GETUTCDATE'


--GET PART OF DATE	
SELECT DATEPART(YEAR,GETDATE())

SELECT DATEPART(YEAR,[employee_createdDate])
FROM
	[dbo].[Employees]
	
SELECT DATEPART(MONTH, GETDATE())

SELECT DATENAME(MONTH, GETDATE())

SELECT DATENAME(WEEK, GETDATE())

SELECT DATENAME(WEEKDAY, GETDATE())


-- Cambiar idioma 
-- SET LANGUAGE 'Spanish';
--Consultar idioma de la base
SELECT @@LANGUAGE


--GET DIFERENCES VALUES FROM
SELECT DATEDIFF(DAY, '2021-06-10', '2021-06-16') AS 'DiasTranscurridos'

SELECT 
	 [e].[employee_name] + ' ' + [e].[employee_lastname]		AS 'Full Name'
	,DATEDIFF(YEAR,[employee_birthday],[employee_createdDate])	AS 'Time'
FROM
	[dbo].[Employees] AS [e]
WHERE
	DATEDIFF(YEAR,[employee_birthday],[employee_createdDate]) = 26;


SELECT DATEDIFF_BIG(NANOSECOND, GETDATE()-1, GETDATE());

--MODIFY DATE
SELECT GETDATE() + 5
--MEJOR UTILIZAR FUNCIÓN
SELECT DATEADD(DAY, 3, GETDATE())
SELECT DATEADD(MONTH, 3, GETDATE())
SELECT DATEADD(YEAR, 3, GETDATE())


--GET LAST DAY BY MONTH
SELECT EOMONTH([employee_birthday]) 
FROM
	[dbo].[Employees]


-- VALIDATION DATES
SELECT ISDATE('ASDADASDSA')		AS 'VALIDATION';
--RETURN 0 IF IT´S INCORRECT
SELECT ISDATE('2021-06-17')		AS 'VALIDATION';
--RETURN 1 IF IT´S CORRECT